version: "3"
services:
    mymongo:
        image: "mongo"
    
    myreader:
            build: .
            depends_on: 
                - mymongo
            ports: 
                - "80:80"